# Generated by Django 5.2.17 on 2026-08-14 10:31

from datetime import timedelta

from django.db import migrations, models
from django.db.models import F


def backfill_expiration(apps, schema_editor):
    workflow_run = apps.get_model("runs", "WorkflowRun")
    workflow_run.objects.filter(expires_at__isnull=True).update(
        expires_at=F("created_at") + timedelta(days=30)
    )


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowrun",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="input_tokens",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="intelligence",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="output_tokens",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_expiration, migrations.RunPython.noop),
    ]
