# Generated by Django 5.2.17 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("runs", "0002_workflowrun_expires_at_workflowrun_input_tokens_and_more")]

    operations = [
        migrations.AddField(
            model_name="workflowrun",
            name="credential_source",
            field=models.CharField(
                blank=True,
                choices=[("personal", "Personal"), ("platform", "Platform")],
                max_length=16,
                null=True,
            ),
        )
    ]
