# Generated by Django 5.2.17 on 2026-08-22 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_providercredential_aws_region_and_more"),
        ("runs", "0003_workflowrun_credential_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowrun",
            name="execution_phase",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("preparing", "Preparing"),
                    ("generating", "Generating"),
                    ("validating", "Validating"),
                    ("saving", "Saving"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="preparing",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="credential_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("personal", "Personal"),
                    ("platform", "Platform"),
                    ("connector", "Local connector"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="model",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name="LocalConnectorJob",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="local_job",
                        serialize=False,
                        to="runs.workflowrun",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("leased", "Leased"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="integrations.localconnector",
                    ),
                ),
            ],
            options={
                "db_table": "local_connector_jobs",
                "indexes": [
                    models.Index(
                        fields=["connector", "status", "created_at"],
                        name="local_conne_connect_1ceabf_idx",
                    )
                ],
            },
        ),
    ]
