# Generated by Django 5.2.17 on 2026-08-23 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('runs', '0004_workflowrun_execution_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='cases.operationscase'),
        ),
    ]
