# Generated by Django 5.2.17 on 2026-08-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("accounts", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ProviderCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("gemini", "Gemini"), ("openai", "OpenAI"), ("qwen", "Qwen")], max_length=32)),
                ("encrypted_api_key", models.TextField()),
                ("key_fingerprint", models.CharField(max_length=16)),
                ("endpoint_region", models.CharField(blank=True, choices=[("singapore", "Singapore"), ("us", "US (Virginia)"), ("beijing", "China (Beijing)")], max_length=32)),
                ("workspace_id", models.CharField(blank=True, max_length=63)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="provider_credentials", to="accounts.appuser")),
            ],
            options={
                "db_table": "provider_credentials",
                "ordering": ["provider"],
                "constraints": [models.UniqueConstraint(fields=("user", "provider"), name="provider_credentials_user_provider_unique")],
            },
        )
    ]
