# Generated by Django 5.2.17 on 2026-08-22 04:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="providercredential",
            name="aws_region",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="providercredential",
            name="base_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="providercredential",
            name="display_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="providercredential",
            name="model_balanced",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="providercredential",
            name="model_fast",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="providercredential",
            name="model_high",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="providercredential",
            name="provider",
            field=models.CharField(
                choices=[
                    ("gemini", "Gemini"),
                    ("openai", "OpenAI"),
                    ("qwen", "Qwen"),
                    ("bedrock", "Amazon Bedrock"),
                    ("custom", "OpenAI-compatible"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="LocalConnector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("token_digest", models.CharField(blank=True, max_length=64)),
                ("pairing_code_digest", models.CharField(blank=True, max_length=64)),
                ("pairing_expires_at", models.DateTimeField(blank=True, null=True)),
                ("paired_at", models.DateTimeField(blank=True, null=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("model_fast", models.CharField(max_length=256)),
                ("model_balanced", models.CharField(max_length=256)),
                ("model_high", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_connector",
                        to="accounts.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "local_connectors",
                "ordering": ["name"],
            },
        ),
    ]
