# Generated by Django 5.2.17 on 2026-08-22 04:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('runs', '0004_workflowrun_execution_phase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowHandoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(choices=[('work-item', 'Work item'), ('meeting-actions', 'Meeting actions'), ('status-update', 'Work status')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('converted', 'Converted')], default='draft', max_length=16)),
                ('draft_input', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('source_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_handoffs', to='runs.workflowrun')),
                ('target_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_handoff', to='runs.workflowrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_handoffs', to='accounts.appuser')),
            ],
            options={
                'db_table': 'workflow_handoffs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=6000)),
                ('kind', models.CharField(choices=[('engineering', 'Engineering defect'), ('verification', 'Configuration verification'), ('investigation', 'Evidence investigation'), ('follow-up', 'Meeting follow-up')], max_length=24)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in-progress', 'In progress'), ('blocked', 'Blocked'), ('done', 'Done')], default='todo', max_length=16)),
                ('assignee_id', models.CharField(blank=True, max_length=64)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_handoff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_item', to='workitems.workflowhandoff')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='runs.workflowrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='accounts.appuser')),
            ],
            options={
                'db_table': 'work_items',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowhandoff',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('user', 'source_run', 'target'), name='one_open_handoff_per_target'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['user', 'status', '-updated_at'], name='work_items_user_id_aa2a43_idx'),
        ),
    ]
