# Generated by Django 5.2.17 on 2026-08-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workitems', '0002_durable_case_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTask',
            fields=[
            ],
            options={
                'verbose_name': 'case task',
                'verbose_name_plural': 'case tasks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('workitems.workitem',),
        ),
        migrations.AddField(
            model_name='workitem',
            name='blocker_reason',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='workitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
