# Generated by Django 5.2.17 on 2026-08-23 07:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Personal workspace', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_workspace', to='accounts.appuser')),
            ],
            options={
                'db_table': 'workspaces',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationsCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=6000)),
                ('summary', models.TextField(blank=True, max_length=3000)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaging', 'Triaging'), ('needs-information', 'Needs information'), ('action-required', 'Action required'), ('in-progress', 'In progress'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=24)),
                ('disposition', models.CharField(choices=[('unclassified', 'Unclassified'), ('product-defect', 'Product defect'), ('configuration-change', 'Configuration change'), ('process-guidance', 'Process guidance'), ('external-dependency', 'External dependency'), ('duplicate', 'Duplicate'), ('needs-more-evidence', 'Needs more evidence')], default='unclassified', max_length=32)),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('resolution_summary', models.TextField(blank=True, max_length=4000)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_operations_cases', to='accounts.appuser')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cases.workspace')),
            ],
            options={
                'db_table': 'operations_cases',
                'ordering': ['-updated_at', '-number'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('initials', models.CharField(max_length=4)),
                ('role', models.CharField(max_length=120)),
                ('discipline', models.CharField(max_length=80)),
                ('focus', models.TextField(blank=True, max_length=1000)),
                ('availability', models.CharField(default='Available', max_length=40)),
                ('workflow_fit', models.JSONField(blank=True, default=list)),
                ('tone', models.CharField(choices=[('indigo', 'Indigo'), ('cyan', 'Cyan'), ('amber', 'Amber'), ('neutral', 'Neutral')], default='neutral', max_length=16)),
                ('is_sample', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_memberships', to='accounts.appuser')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cases.workspace')),
            ],
            options={
                'db_table': 'workspace_members',
                'ordering': ['is_sample', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assignments_made', to='accounts.appuser')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='cases.operationscase')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assignments', to='cases.workspacemember')),
            ],
            options={
                'db_table': 'case_assignments',
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assignment-changed', 'Assignment changed'), ('status-changed', 'Status changed'), ('disposition-changed', 'Disposition changed'), ('workflow-linked', 'Workflow linked'), ('work-item-created', 'Work item created'), ('work-item-updated', 'Work item updated'), ('resolution-recorded', 'Resolution recorded')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_events', to='accounts.appuser')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.operationscase')),
            ],
            options={
                'db_table': 'case_events',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['case', '-created_at'], name='case_events_case_id_9fe0f4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='operationscase',
            index=models.Index(fields=['workspace', 'status', '-updated_at'], name='operations__workspa_317b80_idx'),
        ),
        migrations.AddIndex(
            model_name='operationscase',
            index=models.Index(fields=['workspace', 'disposition', '-updated_at'], name='operations__workspa_254a95_idx'),
        ),
        migrations.AddConstraint(
            model_name='operationscase',
            constraint=models.UniqueConstraint(fields=('workspace', 'number'), name='cases_ws_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['workspace', 'is_active', 'name'], name='workspace_m_workspa_929e24_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacemember',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='cases_ws_member_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='workspacemember',
            constraint=models.UniqueConstraint(condition=models.Q(('app_user__isnull', False)), fields=('workspace', 'app_user'), name='cases_ws_account_uniq'),
        ),
    ]
