# Generated by Django 5.2.17 on 2026-08-23 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0003_backfill_historic_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationscase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operations_cases', to='accounts.appuser'),
        ),
    ]
