# Generated by Django 5.2.17 on 2026-08-23 12:56

import cases.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


def publish_existing_cases(apps, schema_editor):
    OperationsCase = apps.get_model("cases", "OperationsCase")
    for case in OperationsCase.objects.filter(publication_state="draft").iterator():
        OperationsCase.objects.filter(id=case.id).update(
            publication_state="published",
            published_at=case.created_at,
            published_by_id=case.created_by_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0004_alter_operationscase_created_by'),
        ('runs', '0005_workflowrun_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=256)),
                ('intelligence', models.CharField(max_length=16)),
                ('prompt_version', models.CharField(max_length=64)),
                ('evidence_snapshot', models.JSONField(default=list)),
                ('result_json', models.JSONField(default=dict)),
                ('proposed_disposition', models.CharField(choices=[('unclassified', 'Unclassified'), ('product-defect', 'Product defect'), ('configuration-change', 'Configuration change'), ('process-guidance', 'Process guidance'), ('external-dependency', 'External dependency'), ('duplicate', 'Duplicate'), ('needs-more-evidence', 'Needs more evidence')], default='unclassified', max_length=32)),
                ('model_confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('decision_confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('confidence_band', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=12)),
                ('confidence_factors', models.JSONField(default=list)),
                ('is_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'case_assessments',
                'ordering': ['-sequence', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=12)),
                ('text', models.TextField(blank=True, max_length=3000)),
                ('file', models.FileField(blank=True, max_length=500, upload_to=cases.models.case_evidence_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=64)),
                ('byte_size', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'case_evidence',
                'ordering': ['sort_order', 'created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='operationscase',
            name='affected_area',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='operationscase',
            name='constraints',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='operationscase',
            name='environment_context',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='operationscase',
            name='expected_outcome',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='operationscase',
            name='intent',
            field=models.CharField(choices=[('issue', 'Issue investigation'), ('clarification', 'Clarification or guidance'), ('enhancement', 'Additional development')], default='issue', max_length=24),
        ),
        migrations.AddField(
            model_name='operationscase',
            name='publication_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='operationscase',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationscase',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_operations_cases', to='accounts.appuser'),
        ),
        migrations.RunPython(publish_existing_cases, migrations.RunPython.noop),
        migrations.AddField(
            model_name='operationscase',
            name='settings_context',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='caseevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assignment-changed', 'Assignment changed'), ('status-changed', 'Status changed'), ('disposition-changed', 'Disposition changed'), ('workflow-linked', 'Workflow linked'), ('work-item-created', 'Work item created'), ('work-item-updated', 'Work item updated'), ('resolution-recorded', 'Resolution recorded'), ('published', 'Published'), ('archived', 'Archived'), ('evidence-added', 'Evidence added'), ('evidence-removed', 'Evidence removed'), ('assessment-created', 'Assessment created'), ('assessment-applied', 'Assessment applied')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='operationscase',
            index=models.Index(fields=['workspace', 'publication_state', '-updated_at'], name='operations__workspa_411efe_idx'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='cases.operationscase'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assessments', to='accounts.appuser'),
        ),
        migrations.AddField(
            model_name='caseassessment',
            name='source_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assessment', to='runs.workflowrun'),
        ),
        migrations.AddField(
            model_name='caseevidence',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='cases.operationscase'),
        ),
        migrations.AddField(
            model_name='caseevidence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_evidence', to='accounts.appuser'),
        ),
        migrations.AddIndex(
            model_name='caseassessment',
            index=models.Index(fields=['case', '-sequence'], name='case_assess_case_id_ec4fae_idx'),
        ),
        migrations.AddConstraint(
            model_name='caseassessment',
            constraint=models.UniqueConstraint(fields=('case', 'sequence'), name='cases_assessment_sequence_uniq'),
        ),
        migrations.AddIndex(
            model_name='caseevidence',
            index=models.Index(fields=['case', 'created_at'], name='case_eviden_case_id_b3456b_idx'),
        ),
    ]
