# Generated by Django 5.2.17 on 2026-08-24 22:29

import cases.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_owner_access_role(apps, schema_editor):
    WorkspaceMember = apps.get_model("cases", "WorkspaceMember")
    owners = [
        member
        for member in WorkspaceMember.objects.select_related("workspace").iterator()
        if member.app_user_id == member.workspace.owner_id
    ]
    for member in owners:
        member.access_role = "owner"
    WorkspaceMember.objects.bulk_update(owners, ["access_role"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0005_caseassessment_caseevidence_and_more'),
        ('workitems', '0003_casetask_workitem_blocker_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationscase',
            name='published_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_decisions', to='cases.caseassessment'),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='access_role',
            field=models.CharField(choices=[('owner', 'Owner'), ('operator', 'Operator'), ('contributor', 'Contributor'), ('viewer', 'Viewer')], default='contributor', max_length=16),
        ),
        migrations.RunPython(backfill_owner_access_role, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='caseevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assignment-changed', 'Assignment changed'), ('status-changed', 'Status changed'), ('disposition-changed', 'Disposition changed'), ('workflow-linked', 'Workflow linked'), ('work-item-created', 'Work item created'), ('work-item-updated', 'Work item updated'), ('resolution-recorded', 'Resolution recorded'), ('published', 'Published'), ('archived', 'Archived'), ('evidence-added', 'Evidence added'), ('evidence-removed', 'Evidence removed'), ('assessment-created', 'Assessment created'), ('assessment-applied', 'Assessment applied'), ('update-added', 'Update added'), ('task-created', 'Task created'), ('task-updated', 'Task updated'), ('verification-recorded', 'Verification recorded')], max_length=32),
        ),
        migrations.AlterField(
            model_name='operationscase',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('triaging', 'Triaging'), ('needs-information', 'Needs information'), ('action-required', 'Action required'), ('in-progress', 'In progress'), ('verification', 'Verification'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=24),
        ),
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_type', models.CharField(choices=[('progress', 'Progress'), ('blocker', 'Blocker'), ('decision', 'Decision'), ('clarification', 'Clarification'), ('resolution', 'Resolution proposal'), ('verification', 'Verification')], max_length=20)),
                ('body', models.TextField(max_length=6000)),
                ('external_links', models.JSONField(blank=True, default=list)),
                ('verification_result', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=12)),
                ('client_request_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_updates', to='accounts.appuser')),
                ('author_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_case_updates', to='cases.workspacemember')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='cases.operationscase')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_updates', to='workitems.workitem')),
            ],
            options={
                'db_table': 'case_updates',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CaseUpdateAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=cases.models.case_update_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=64)),
                ('byte_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.caseupdate')),
            ],
            options={
                'db_table': 'case_update_attachments',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseDomainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_domain_events', to='accounts.appuser')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_events', to='cases.operationscase')),
            ],
            options={
                'db_table': 'case_domain_events',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['delivered_at', 'created_at'], name='case_domain_deliver_4a1ac0_idx'), models.Index(fields=['case', 'created_at'], name='case_domain_case_id_6ea87a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='caseupdate',
            index=models.Index(fields=['case', '-created_at'], name='case_update_case_id_a817f0_idx'),
        ),
        migrations.AddIndex(
            model_name='caseupdate',
            index=models.Index(fields=['author_member', '-created_at'], name='case_update_author__a47423_idx'),
        ),
        migrations.AddConstraint(
            model_name='caseupdate',
            constraint=models.UniqueConstraint(fields=('case', 'client_request_id'), name='cases_update_request_uniq'),
        ),
        migrations.AddIndex(
            model_name='caseupdateattachment',
            index=models.Index(fields=['update', 'created_at'], name='case_update_update__26eed3_idx'),
        ),
    ]
