# Generated by Django 5.2.17 on 2026-08-24 23:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_membership_lifecycle(apps, schema_editor):
    WorkspaceMember = apps.get_model("cases", "WorkspaceMember")
    WorkspaceMember.objects.filter(is_sample=True).update(membership_state="sample")
    WorkspaceMember.objects.filter(is_sample=False, is_active=True).update(
        membership_state="active",
        joined_at=models.F("created_at"),
    )
    WorkspaceMember.objects.filter(is_active=False).update(membership_state="inactive")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cases', '0006_operationscase_published_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='collaboration_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='collaboration_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='workspace',
            name='collaboration_state',
            field=models.CharField(choices=[('personal', 'Personal'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('error', 'Error')], default='personal', max_length=16),
        ),
        migrations.AddField(
            model_name='workspace',
            name='workos_organization_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='workos_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='external_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='membership_state',
            field=models.CharField(choices=[('sample', 'Sample profile'), ('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='workos_membership_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(backfill_membership_lifecycle, migrations.RunPython.noop),
        migrations.CreateModel(
            name='WorkOSEventReceipt',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=120)),
                ('workos_organization_id', models.CharField(blank=True, max_length=255)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('external_updated_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workos_event_receipts',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['workos_organization_id', '-received_at'], name='workos_even_workos__0bd4fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('access_role', models.CharField(choices=[('owner', 'Owner'), ('operator', 'Operator'), ('contributor', 'Contributor'), ('viewer', 'Viewer')], default='contributor', max_length=16)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('workos_invitation_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('external_updated_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_invitations_accepted', to='accounts.appuser')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_invitations_sent', to='accounts.appuser')),
                ('target_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_invitations', to='cases.workspacemember')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='cases.workspace')),
            ],
            options={
                'db_table': 'workspace_invitations',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['workspace', 'state', '-created_at'], name='workspace_i_workspa_a2eeb8_idx')],
                'constraints': [
                    models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('workspace', 'email'), name='cases_ws_pending_invite_uniq'),
                    models.UniqueConstraint(condition=models.Q(('state', 'pending'), ('target_member__isnull', False)), fields=('workspace', 'target_member'), name='cases_ws_pending_target_uniq'),
                ],
            },
        ),
    ]
