# Generated by Django 5.2.17 on 2026-08-25 21:49

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.utils import timezone


def backfill_notification_defaults(apps, schema_editor):
    CaseDomainEvent = apps.get_model("cases", "CaseDomainEvent")
    Workspace = apps.get_model("cases", "Workspace")
    WorkspaceMember = apps.get_model("cases", "WorkspaceMember")
    WorkspaceNotificationPolicy = apps.get_model("cases", "WorkspaceNotificationPolicy")
    MemberNotificationPreference = apps.get_model("cases", "MemberNotificationPreference")
    WorkspaceNotificationPolicy.objects.bulk_create(
        [
            WorkspaceNotificationPolicy(workspace_id=value)
            for value in Workspace.objects.values_list("id", flat=True)
        ],
        ignore_conflicts=True,
    )
    eligible_members = WorkspaceMember.objects.filter(
        app_user__isnull=False,
        is_sample=False,
        is_active=True,
    ).values_list("id", flat=True)
    MemberNotificationPreference.objects.bulk_create(
        [MemberNotificationPreference(member_id=value) for value in eligible_members],
        ignore_conflicts=True,
    )
    # Events created before notification delivery existed must not fan out retroactively on deploy.
    CaseDomainEvent.objects.filter(processed_at__isnull=True).update(processed_at=timezone.now())


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("cases", "0007_workspace_collaboration_enabled_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseUpdateMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "case_update_mentions",
            },
        ),
        migrations.CreateModel(
            name="MemberNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("assignment_email", models.BooleanField(blank=True, null=True)),
                ("blocker_email", models.BooleanField(blank=True, null=True)),
                ("mention_email", models.BooleanField(blank=True, null=True)),
                ("resolution_email", models.BooleanField(blank=True, null=True)),
                ("verification_email", models.BooleanField(blank=True, null=True)),
                ("due_date_email", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "member_notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("assignment", "Assignment"),
                            ("blocker", "Blocker"),
                            ("mention", "Mention"),
                            ("resolution", "Resolution"),
                            ("verification", "Verification"),
                            ("due-date", "Due date"),
                            ("published", "Published"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=500)),
                ("action_path", models.CharField(max_length=500)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("retry", "Retry"),
                            ("failed", "Failed"),
                            ("suppressed", "Suppressed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField()),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=80)),
                ("last_error_message", models.CharField(blank=True, max_length=500)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_deliveries",
                "ordering": ["next_attempt_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("outcome", models.CharField(max_length=32)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notification_delivery_attempts",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ResendWebhookReceipt",
            fields=[
                ("event_id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=80)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "resend_webhook_receipts",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceNotificationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("assignment_email", models.BooleanField(default=True)),
                ("blocker_email", models.BooleanField(default=True)),
                ("mention_email", models.BooleanField(default=True)),
                ("resolution_email", models.BooleanField(default=True)),
                ("verification_email", models.BooleanField(default=True)),
                ("due_date_email", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workspace_notification_policies",
            },
        ),
        migrations.RemoveIndex(
            model_name="casedomainevent",
            name="case_domain_deliver_4a1ac0_idx",
        ),
        migrations.RenameField(
            model_name="casedomainevent",
            old_name="delivered_at",
            new_name="processed_at",
        ),
        migrations.AddIndex(
            model_name="casedomainevent",
            index=models.Index(
                fields=["processed_at", "created_at"], name="case_domain_process_524634_idx"
            ),
        ),
        migrations.AddField(
            model_name="caseupdatemention",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_update_mentions",
                to="cases.workspacemember",
            ),
        ),
        migrations.AddField(
            model_name="caseupdatemention",
            name="update",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentions",
                to="cases.caseupdate",
            ),
        ),
        migrations.AddField(
            model_name="membernotificationpreference",
            name="member",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preference",
                to="cases.workspacemember",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="cases.operationscase",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="cases.casedomainevent",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="cases.workspacemember",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="cases.workspace",
            ),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="notification",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_delivery",
                to="cases.notification",
            ),
        ),
        migrations.AddField(
            model_name="notificationdeliveryattempt",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="cases.notificationdelivery",
            ),
        ),
        migrations.AddField(
            model_name="workspacenotificationpolicy",
            name="workspace",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_policy",
                to="cases.workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="caseupdatemention",
            constraint=models.UniqueConstraint(
                fields=("update", "member"), name="cases_update_member_mention_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "read_at", "-created_at"],
                name="notificatio_recipie_66fbe3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["workspace", "-created_at"], name="notificatio_workspa_5e4b93_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("event", "recipient"), name="cases_event_recipient_notification_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["status", "next_attempt_at"], name="notificatio_status_98579e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationdeliveryattempt",
            constraint=models.UniqueConstraint(
                fields=("delivery", "attempt_number"), name="cases_delivery_attempt_number_uniq"
            ),
        ),
        migrations.RunPython(backfill_notification_defaults, migrations.RunPython.noop),
    ]
